script:
- "build/deploy.rb"

language: ruby
cache: bundler

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.com dashboard, marked secure
  keep-history: true
  on:
    branch: master

after_script:
- "build/rebuild_facebook_previews.rb"